name: Build and deploy cobra website (.Net framework 4.6) to Azure Web App (Windows)
 
env:
  AZURE_WEBAPP_NAME_DEV: cobra-webapp
  AZURE_WEBAPP_NAME_STAGE: stg-cobra-dotnet-webapp
  AZURE_WEBAPP_NAME: cobra-dotnet-webapp
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  SLN_FILE: cobrawebsite.sln
  WEBSITE_PROJECT: cobrawebsite

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: 

permissions:
  contents: read 

jobs:
  build:
    runs-on: windows-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore packages
        run: |
          # Clean and restore packages
          if (Test-Path "packages") { Remove-Item -Path "packages" -Recurse -Force }
          # Nuget restore for class libraries if any
          nuget restore ${{ env.SLN_FILE }} -PackagesDirectory packages
          # Nuget restore for website project if packages.config exists
          if (Test-Path "${{ env.WEBSITE_PROJECT }}\packages.config") {
            nuget restore "${{ env.WEBSITE_PROJECT }}\packages.config" -PackagesDirectory packages
          }

      - name: Build Solution
        run: |
          msbuild ${{ env.SLN_FILE }} /p:Configuration=Release /p:Platform="Any CPU"
          
      - name: Copy dependencies from nuget and build
        run: |
          if (!(Test-Path "${{ env.WEBSITE_PROJECT }}\Bin")) { New-Item -ItemType Directory -Path "${{ env.WEBSITE_PROJECT }}\Bin" -Force }
          Get-ChildItem -Path "packages" -Recurse -Filter "*.dll" | Copy-Item -Destination "${{ env.WEBSITE_PROJECT }}\Bin\" -Force      

      - name: Publish website
        run: |
          C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_compiler.exe -v / -p ${{ env.WEBSITE_PROJECT }} -f -u publish
          Copy-Item -Path "${{ env.WEBSITE_PROJECT }}\Bin\*" -Destination "publish\Bin\" -Recurse -Force
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cobra-app
          path: publish

  # deploytodev:
  #   permissions:
  #     contents: none
  #   runs-on: windows-latest
  #   needs: build
  #   environment:
  #     name: 'Development'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
  #         publish-profile: ${{ secrets.devgithubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # deploytostage:
  #    permissions:
  #     contents: none
  #    runs-on: windows-latest
  #    needs: deploytodev
  #    environment:
  #     name: 'Stage'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #    steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME_STAGE }}
  #         publish-profile: ${{ secrets.stggithubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # deploytoproduction:
  #   permissions:
  #     contents: none
  #   runs-on: windows-latest
  #   needs: deploytostage
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.githubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}