name: Build and deploy ASP.Net framework 4.6 app to an Azure Web App
 
env:
  AZURE_WEBAPP_NAME_DEV: dev-cobra-dotnet-webapp
  AZURE_WEBAPP_NAME_STAGE: stg-cobra-dotnet-webapp
  AZURE_WEBAPP_NAME: cobra-dotnet-webapp
  AZURE_WEBAPP_PACKAGE_PATH: '.'

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: 
permissions:
  contents: read 
jobs:
  build:
    runs-on: windows-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages for class library
        run: nuget restore Cobra.Data\Cobra.Data.csproj

      - name: Install packages for website
        run: |
          nuget install cobrawebsite\packages.config -OutputDirectory packages
          nuget install Cobra.Data\packages.config -OutputDirectory packages

      - name: Build Cobra.Data project
        run: |
          msbuild Cobra.Data\Cobra.Data.csproj `
          /p:Configuration=Release `
          /p:Platform="Any CPU"

      - name: Copy dependencies to website Bin folder
        run: |
          # Ensure cobrawebsite\Bin directory exists
          if (!(Test-Path "cobrawebsite\Bin")) { New-Item -ItemType Directory -Path "cobrawebsite\Bin" -Force }
          
          # Copy Cobra.Data output
          Copy-Item -Path "Cobra.Data\bin\Release\Cobra.Data.dll" -Destination "cobrawebsite\Bin\" -Force
          
          # Copy package dependencies from packages folder to website Bin
          Get-ChildItem -Path "packages" -Recurse -Filter "*.dll" | Where-Object { $_.Directory.Name -like "*net4*" -or $_.Directory.Name -like "*lib*" } | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination "cobrawebsite\Bin\" -Force -ErrorAction SilentlyContinue
          }

      - name: Precompile and publish website
        run: |
          # Precompile the website
          C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_compiler.exe `
          -v / -p cobrawebsite -f -u publish
          
          # Copy Bin directory with all dependencies
          if (Test-Path "cobrawebsite\Bin") {
            Copy-Item -Path "cobrawebsite\Bin\*" -Destination "publish\Bin\" -Recurse -Force
          }
          
          Write-Host "Published website with dependencies"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cobra-app
          path: publish

  # deploytodev:
  #   permissions:
  #     contents: none
  #   runs-on: windows-latest
  #   needs: build
  #   environment:
  #     name: 'Development'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
  #         publish-profile: ${{ secrets.devgithubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # deploytostage:
  #    permissions:
  #     contents: none
  #    runs-on: windows-latest
  #    needs: deploytodev
  #    environment:
  #     name: 'Stage'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #    steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME_STAGE }}
  #         publish-profile: ${{ secrets.stggithubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # deploytoproduction:
  #   permissions:
  #     contents: none
  #   runs-on: windows-latest
  #   needs: deploytostage
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.githubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}