name: Build and deploy ASP.Net framework 4.6 app to an Azure Web App
 
env:
  AZURE_WEBAPP_NAME_DEV: dev-cobra-dotnet-webapp
  AZURE_WEBAPP_NAME_STAGE: stg-cobra-dotnet-webapp
  AZURE_WEBAPP_NAME: cobra-dotnet-webapp
  AZURE_WEBAPP_PACKAGE_PATH: '.'

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: 

permissions:
  contents: read 

jobs:
  build:
    runs-on: windows-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore packages and build
        run: |
          # Clean and restore packages
          Remove-Item -Path "packages" -Recurse -Force -ErrorAction SilentlyContinue
          # Nuget restore for class libraries if any
          nuget restore cobrawebsite.sln -PackagesDirectory packages
          # Nuget restore for website project if packages.config exists
          if (Test-Path "cobrawebsite\packages.config") {
            nuget restore "cobrawebsite\packages.config" -PackagesDirectory packages
          }

          # Build solution
          msbuild cobrawebsite.sln /p:Configuration=Release /p:Platform="Any CPU"
          
          # Copy dependencies from nuget and build
          New-Item -ItemType Directory -Path "cobrawebsite\Bin" -Force -ErrorAction SilentlyContinue
          Get-ChildItem -Path "packages" -Recurse -Filter "*.dll" | Where-Object { $_.Directory.Name -like "net4*" } | Copy-Item -Destination "cobrawebsite\Bin\" -Force
          
      - name: Publish website
        run: |
          C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet_compiler.exe -v / -p cobrawebsite -f -u publish
          Copy-Item -Path "cobrawebsite\Bin\*" -Destination "publish\Bin\" -Recurse -Force
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cobra-app
          path: publish

  # deploytodev:
  #   permissions:
  #     contents: none
  #   runs-on: windows-latest
  #   needs: build
  #   environment:
  #     name: 'Development'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
  #         publish-profile: ${{ secrets.devgithubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # deploytostage:
  #    permissions:
  #     contents: none
  #    runs-on: windows-latest
  #    needs: deploytodev
  #    environment:
  #     name: 'Stage'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #    steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME_STAGE }}
  #         publish-profile: ${{ secrets.stggithubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # deploytoproduction:
  #   permissions:
  #     contents: none
  #   runs-on: windows-latest
  #   needs: deploytostage
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cobra-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.githubsecretappdeployment }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}